name: Deploy Frontend
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t kodi73/docker-react2 -f Dockerfile.dev .
      - run: docker run -e CI=true kodi73/docker-react2 npm test